<?php
/**
 * PhpStorm.
 * User: Jay
 * Date: 2018/4/20
 */

namespace PHPZlc\PHPZlc\Bundle\Command;


use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;

abstract class Base extends Command
{
    /**
     * @var SymfonyStyle
     */
    protected $io;

    protected $command_pre = 'phpzlc:';

    protected $description_pre = '[phpzlc] ';

    protected function getRootPath()
    {
        return  dirname(dirname(dirname(dirname(dirname(dirname(dirname(__FILE__)))))));
    }

    protected function interact(InputInterface $input, OutputInterface $output)
    {
        parent::interact($input, $output); // TODO: Change the autogenerated stub

        $this->io = new SymfonyStyle($input, $output);
    }
}